### ISSUE TITLE
How to get "token_embed_c100.npy"?

### ISSUE THREAD

**Issue by HengGao12** [deeplearning-wisc/dream-ood#10]
Hello, dear author, I would like to know how you get the "token_embed_c100.npy" and "token_embed_in100.npy"?

**Comment by d12306** [comment]
hi, @HengGao12 , it is simply through taking the token embedding of the 100 class names in the token embedding table of stable diffusion model (text encoder).

**Comment by wangpuyi** [comment]
Could you please show the code? So it will be much easier for us when testing your project.

 Thank your very much
