### ISSUE TITLE
epoch size

### ISSUE THREAD

**Issue by suheey** [deeplearning-wisc/dream-ood#11]
Hello,

When training a model with outliers as described in your script **train_ood_det_in100.py**, the choice of epoch size is an important factor that can influence the performance and convergence of the model. In your case, you mentioned that the epoch size is set to 100, which is different from the more typical 300 epochs often used in other papers when applying cosine annealing.

I'm wondering did you checked that model enoughly trained for id-multi-classification accuracy.

**Comment by d12306** [comment]
hi @suheey , i chose 100 because of limitation resources and you can definitely train more for epochs.

the id accuracy is also reported in the paper, which looks pretty reasonable.
