### ISSUE TITLE
Inquery about the accuracy reported in paper

### ISSUE THREAD

**Issue by WenjieZhao1** [deeplearning-wisc/dream-ood#12]
Hello,

When I trying to evaluate the model provided in repo:https://drive.google.com/file/d/1nOWX3qr-_k-5B6Lyp3tfp5GVMWuMGwWc/view?usp=sharing on imagenet100 and iNat,Places,SUN,texture, as OOD dataset, the result didn't get the number reported in the papar. I think maybe I ignore some setting or something else. Could you please give me advice to achieve the accuracy reported in paper?
<img width="497" alt="image" src="https://github.com/deeplearning-wisc/dream-ood/assets/50863717/f75e130f-0822-41b3-8ee8-aaf04d9b3f5f">

Hope to get your reply. Thank you.

**Comment by d12306** [comment]
hi @WenjieZhao1 , i have just ran the code and found that my result is pretty close to the reported one, not sure the reason, did you download the right test data?

![Uploading 截屏2024-05-30 上午9.34.12.png…]()
