### ISSUE TITLE
xformers version

### ISSUE THREAD

**Issue by mueller-mp** [deeplearning-wisc/dream-ood#14]
Hi! 
I'm trying to reproduce your results, but I keep getting into trouble at step 3 (Synthesizing outliers in the pixel space), because the xformer version seems to be wrong. The latest xformer version requires pytorch 2.2.0, and with this your code doesn't run anymore. 
Could you specify which xformers version you used?
Thanks!

**Comment by d12306** [comment]
hi, @mueller-mp , please check https://github.com/deeplearning-wisc/dream-ood/issues/7

**Comment by mueller-mp** [comment]
Thanks, should have seen this.
