### ISSUE TITLE
Question about the `gan` parameter usage

### ISSUE THREAD

**Issue by chalengr** [deeplearning-wisc/dream-ood#15]
Hello,

First of all, thank you for sharing your code. It has been very helpful for my research.

I noticed that the `gan` parameter is defined in the code, but it does not seem to affect the training process. I am interested in incorporating GAN-generated data into my training. Could you please provide some guidance or an example of how to properly use the `gan` parameter in this context?

Here is a snippet of the code where the `gan` parameter is defined but not utilized:

```python
parser.add_argument('--gan', type=int, default=0)

Thank you for your time and assistance.

**Comment by d12306** [comment]
hi @chalengr , please check the code https://github.com/alinlab/Confident_classifier for implementation!

**Comment by chalengr** [comment]
> hi @chalengr , please check the code https://github.com/alinlab/Confident_classifier for implementation!

I encountered difficulties in applying the 224x224 ImageNet images to the code you mentioned. Could you provide some of the code you used in your experiments?
