### ISSUE TITLE
Generated images link issue

### ISSUE THREAD

**Issue by leesanghoon421** [deeplearning-wisc/dream-ood#19]
Generated images: [outlier image for IN100](https://github.com/deeplearning-wisc/dream-ood/blob/main), [inlier image for IN100](https://github.com/deeplearning-wisc/dream-ood/blob/main) and [outlier image for cifar100](https://github.com/deeplearning-wisc/dream-ood/blob/main).

When I press the link of outlier image for IN100 / inlier image for IN100 / outlier image for cifar100, page just go backs to main page. Where can I download or take a look of example Outlier images?

**Comment by cviviers** [comment]
Any update on where we can access these?

**Comment by leesanghoon421** [comment]
@cviviers If you look at the todo part of GitHub readme, you can see that the link is expired.

**Comment by cviviers** [comment]
I thought the authors might have directly shared an updated link with you. Maybe reopen the issue?

**Comment by leesanghoon421** [comment]
@cviviers I ran the code and got the data myself. I think it's ok to reopen the issue for me. If you got problem, you might open the new issue. Thanks for comment. Good Luck.
