### ISSUE TITLE
cifar100_initialization_weight

### ISSUE THREAD

**Issue by XixiLiu95** [deeplearning-wisc/dream-ood#5]
Hello Xuefeng,

You mention that the pre-trained classifiers are used for weight initialization to save time. I can find the checkpoint for ImageNet-100 but not for CIFAR100, could you please share the corresponding checkpoint?

Thanks a lot!
 /Xixi

**Comment by d12306** [comment]
Hi @XixiLiu95 , note that the model is trained from scratch for cifar-100
.

**Comment by XixiLiu95** [comment]
Aha, ok. Thanks for the quick reply.
