### ISSUE TITLE
About the generation of fake images.

### ISSUE THREAD

**Issue by Cverchen** [deeplearning-wisc/dream-ood#6]
Hello, Xuefeng!
When i want to generate fake ood images by outlier embeddings of cifar100 , the program says: 'TypeError: get_learned_conditioning() takes 2 positional arguments but 4 were given'，and get_learned_conditioning() is not been found.
How can i solve it?
Thanks for your reply.

**Comment by d12306** [comment]
Hi @Cverchen , unfortunately i did not reproduce the error. Can you share you command line?

**Comment by Cverchen** [comment]
When i use the following command line to generate fake ood images for cifar100:
         python scripts/dream_ood.py --plms --n_iter 50 --n_samples 3 --outdir txt2img-samples-cifar100 --loaded_embedding 
         outlier_cifar100.npy --ckpt sd-v1-4.ckpt --id_data cifar100 --skip_grid
It produced the error:
  File "scripts/dream_ood.py", line 453, in main
    uc = model.get_learned_conditioning(batch_size * [""], 0, opt)
TypeError: get_learned_conditioning() takes 2 positional arguments but 4 were given

**Comment by d12306** [comment]
Hi @Cverchen , my run is successful though

![image](https://github.com/deeplearning-wisc/dream-ood/assets/42554178/65641973-e358-4a50-9b69-04bcec7fa3c5)

can you download the latest code and test?
