### ISSUE TITLE
The version of xformers used in your code?

### ISSUE THREAD

**Issue by HengGao12** [deeplearning-wisc/dream-ood#7]
Hello, dear author, I want to know what's the version of xformers used in your code?

**Comment by d12306** [comment]
Hi @HengGao12 , I used 0.13.0-dev

**Comment by HengGao12** [comment]
> Hi @HengGao12 , I used 0.13.0-dev

okok，感谢！

**Comment by yoonsanghyu** [comment]
Where can i find `xformers==0.13.0-dev`? I only found `xformers==0.0.13` in here, https://pypi.org/project/xformers/0.0.13/.

**Comment by HengGao12** [comment]
> Where can i find `xformers==0.13.0-dev`? I only found `xformers==0.0.13` in here, https://pypi.org/project/xformers/0.0.13/.
Yes, you can use 'xformers==0.0.13', which works successfully.

**Comment by HengGao12** [comment]
> Where can i find `xformers==0.13.0-dev`? I only found `xformers==0.0.13` in here, https://pypi.org/project/xformers/0.0.13/.

1

**Comment by HengGao12** [comment]
> Where can i find `xformers==0.13.0-dev`? I only found `xformers==0.0.13` in here, https://pypi.org/project/xformers/0.0.13/.

Yes, you can use `xformers==0.0.13`, which works successfully.

**Comment by leesanghoon421** [comment]
> > Where can i find `xformers==0.13.0-dev`? I only found `xformers==0.0.13` in here, https://pypi.org/project/xformers/0.0.13/.
> 
> Yes, you can use `xformers==0.0.13`, which works successfully.

I’m sorry to bother you. I’m having a problem running code using xformers==0.0.13, and I would like to ask for your help. When I run pip install xformers==0.0.13, torch gets updated to the latest version and the code doesn’t run. Is the situation below normal, and should I have to look for other issue?

    Found existing installation: torch 1.11.0
    Uninstalling torch-1.11.0:
      Successfully uninstalled torch-1.11.0
Successfully installed mpmath-1.3.0 mypy-extensions-1.0.0 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.20.5 nvidia-nvjitlink-cu12-12.5.82 nvidia-nvtx-cu12-12.1.105 pyre-extensions-0.0.23 sympy-1.13.0 torch-2.3.1 triton-2.3.1 typing-inspect-0.9.0 xformers-0.0.13
