### ISSUE TITLE
Code for TSNE plot as provided in paper.

### ISSUE THREAD

**Issue by spandan12** [deeplearning-wisc/dream-ood#8]
Hi,

I was trying to recreate the TSNE plot as provided in figure 3 of the paper. Can you provide the code for this specific plot? Also, which dataset is this created for? 
<img width="372" alt="image" src="https://github.com/deeplearning-wisc/dream-ood/assets/33442589/3a48952f-8724-4bf3-bcd0-5140901d251c">

**Comment by d12306** [comment]
hi @spandan12 , thanks for your question. The TSNE code is very simple (loading the embeddings and use the plot api). and the embeddings are already provided in the readme file. 


The plot id for Cifar100.

**Comment by spandan12** [comment]
sure thanks.
